name: Package and Publish Artifact

on:
  push:
    branches:
      - main # Ajusta al branch principal que uses
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Package application
      run: |
        mkdir -p output
        tar -czf output/app.tar.gz app/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-artifact
        path: output/app.tar.gz
